# Generated by Django 4.2.2 on 2023-07-11 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourist_app', '0007_reg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='reg',
        ),
    ]
