# Generated by Django 4.2.2 on 2023-07-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist_app', '0009_reg'),
    ]

    operations = [
        migrations.CreateModel(
            name='londonfield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addresslondon', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
