# Generated by Django 4.2.2 on 2023-07-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist_app', '0011_alter_londonfield_addresslondon'),
    ]

    operations = [
        migrations.AddField(
            model_name='londonfield',
            name='addresslondon1',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='londonfield',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='londonfield',
            name='date1',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='londonfield',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='londonfield',
            name='gender1',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10, null=True),
        ),
    ]
