# Generated by Django 4.2.2 on 2023-07-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist_app', '0012_londonfield_addresslondon1_londonfield_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='londonfield',
            name='addresslondon',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='londonfield',
            name='addresslondon1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='londonfield',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='londonfield',
            name='gender1',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
