# Generated by Django 4.2.2 on 2023-07-19 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourist_app', '0014_china'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='china',
            new_name='chinafield',
        ),
    ]
