# Generated by Django 4.2.2 on 2023-07-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist_app', '0023_bookingfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingfield',
            name='destination',
            field=models.CharField(choices=[('1', 'Shimla'), ('2', 'Kovalam'), ('3', 'Leh Ladakh'), ('4', 'Andaman'), ('5', 'Sikkim')], max_length=30, null=True),
        ),
    ]
