# Generated by Django 4.2.2 on 2023-07-20 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourist_app', '0024_alter_bookingfield_destination'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bookingfield',
            new_name='packagefield',
        ),
    ]
