# Generated by Django 4.2.2 on 2023-07-20 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist_app', '0025_rename_bookingfield_packagefield'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookingfield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=30, null=True)),
                ('date', models.DateField(null=True)),
                ('destination', models.CharField(choices=[('1', 'Shimla'), ('2', 'Kovalam'), ('3', 'Leh Ladakh'), ('4', 'Andaman'), ('5', 'Sikkim')], max_length=30, null=True)),
                ('special', models.CharField(max_length=150, null=True)),
            ],
        ),
    ]
