# Generated by Django 4.2.2 on 2023-07-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist_app', '0026_bookingfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagefield',
            name='special',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
