# Generated by Django 4.2.2 on 2023-07-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist_app', '0027_alter_packagefield_special'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagefield',
            name='destination',
            field=models.CharField(choices=[('Shimla', 'Shimla'), ('Kovalam', 'Kovalam'), ('Leh Ladakh', 'Leh Ladakh'), ('Andaman', 'Andaman'), ('Sikkim', 'Sikkim')], max_length=30, null=True),
        ),
    ]
