# Generated by Django 4.2.2 on 2023-07-22 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist_app', '0030_alter_bookingfield_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='londonfield',
            name='date2',
            field=models.DateField(null=True),
        ),
    ]
