# Generated by Django 4.2.2 on 2023-07-22 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist_app', '0031_londonfield_date2'),
    ]

    operations = [
        migrations.AddField(
            model_name='chinafield',
            name='date2',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='indonesiafield',
            name='date2',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='japanfield',
            name='date2',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='malaysiafield',
            name='date2',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='singaporefield',
            name='date2',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='thailandfield',
            name='date2',
            field=models.DateField(null=True),
        ),
    ]
