# Generated by Django 4.2.2 on 2023-07-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist_app', '0032_chinafield_date2_indonesiafield_date2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='londonfield',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
