# Generated by Django 4.2.2 on 2023-07-25 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist_app', '0035_remove_londonfield_age1_remove_londonfield_age2'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentMethod', models.CharField(max_length=30, null=True)),
                ('name', models.CharField(max_length=30, null=True)),
                ('cardnumber', models.CharField(max_length=16, null=True)),
                ('expiration', models.DateField(null=True)),
                ('cvv', models.CharField(max_length=3, null=True)),
            ],
        ),
    ]
