# Generated by Django 4.2.2 on 2023-07-25 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist_app', '0036_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='expiration',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
