# Generated by Django 4.2.2 on 2023-07-28 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourist_app', '0037_alter_payment_expiration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='londonfield',
            old_name='date',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='londonfield',
            old_name='date1',
            new_name='age1',
        ),
    ]
