# Generated by Django 4.2.2 on 2023-07-29 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourist_app', '0039_rename_addresslondon_londonfield_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chinafield',
            old_name='date',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='chinafield',
            old_name='date1',
            new_name='age1',
        ),
        migrations.RenameField(
            model_name='chinafield',
            old_name='addresschina',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='chinafield',
            old_name='addresschina1',
            new_name='name1',
        ),
    ]
