# Generated by Django 4.2.2 on 2023-07-29 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourist_app', '0041_payment_one'),
    ]

    operations = [
        migrations.RenameField(
            model_name='singaporefield',
            old_name='date',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='singaporefield',
            old_name='date1',
            new_name='age1',
        ),
        migrations.RenameField(
            model_name='singaporefield',
            old_name='addresssingapore',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='singaporefield',
            old_name='addresssingapore1',
            new_name='name1',
        ),
    ]
