# Generated by Django 4.2.2 on 2023-07-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist_app', '0043_payment_two'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment_three',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentMethod', models.CharField(max_length=30, null=True)),
                ('name', models.CharField(max_length=30, null=True)),
                ('cardnumber', models.CharField(max_length=16, null=True)),
                ('expiration', models.CharField(max_length=20, null=True)),
                ('cvv', models.CharField(max_length=3, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='indonesiafield',
            old_name='date',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='indonesiafield',
            old_name='date1',
            new_name='age1',
        ),
        migrations.RenameField(
            model_name='indonesiafield',
            old_name='addressindonesia',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='indonesiafield',
            old_name='addressindonesia1',
            new_name='name1',
        ),
        migrations.RenameField(
            model_name='japanfield',
            old_name='date',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='japanfield',
            old_name='date1',
            new_name='age1',
        ),
        migrations.RenameField(
            model_name='japanfield',
            old_name='addressjapan',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='japanfield',
            old_name='addressjapan1',
            new_name='name1',
        ),
        migrations.RenameField(
            model_name='malaysiafield',
            old_name='date',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='malaysiafield',
            old_name='date1',
            new_name='age1',
        ),
        migrations.RenameField(
            model_name='malaysiafield',
            old_name='addressmalaysia',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='malaysiafield',
            old_name='addressmalaysia1',
            new_name='name1',
        ),
        migrations.RenameField(
            model_name='thailandfield',
            old_name='date',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='thailandfield',
            old_name='date1',
            new_name='age1',
        ),
        migrations.RenameField(
            model_name='thailandfield',
            old_name='addressthailand',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='thailandfield',
            old_name='addressthailand1',
            new_name='name1',
        ),
    ]
