# Generated by Django 4.2.2 on 2023-07-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist_app', '0047_payment_seven'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingfield',
            name='date',
            field=models.DateField(max_length=50, null=True),
        ),
    ]
