# Generated by Django 4.2.2 on 2023-07-30 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourist_app', '0049_alter_bookingfield_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='packagefield',
        ),
    ]
